const MONSTER_RECIPES = {
    "Rejuvenating": [ "Gargantuan", "Vampiric" ],
    "Corrupter": ["Bloodletter", "Chaosweaver"],
    "Assassin": ["Deadeye", "Vampiric"],
    "Hexer": ["Chaosweaver", "Echoist"],
    "Entangler": ["Toxic", "Bloodletter"],
    "Necromancer": ["Bombardier", "Overcharged"],
    "Drought Bringer": ["Malediction", "Deadeye"],
    "Evocationist": ["Flameweaver", "Frostweaver", "Stormweaver"],
    "Treant Horde": ["Toxic", "Sentinel", "Steel-Infused"],
    "Invulnerable": ["Sentinel", "Juggernaut", "Consecrator"],
    "Frost Strider": ["Frostweaver", "Hasted"],
    "Storm Strider": ["Stormweaver", "Hasted"],
    "Flame Strider": ["Flameweaver", "Hasted"],
    "Executioner": ["Frenzied", "Berserker"],
    "Magma Barrier": ["Incendiary", "Bonebreaker"],
    "Ice Prison": ["Permafrost", "Sentinel"],
    "Heralding Minions": ["Dynamo", "Arcane Buffer"],
    "Mana Siphoner": ["Consecrator", "Dynamo"],
    "Mirror Image": ["Echoist", "Soul Conduit"],
    "Empowering Minions": ["Necromancer", "Executioner", "Gargantuan"],
    "Effigy": ["Hexer", "Malediction", "Corrupter"],
    "Crystal-Skinned": ["Rejuvenating", "Permafrost", "Berserker"],
    "Temporal Bubble": ["Juggernaut", "Hexer", "Arcane Buffer"],
    "Empowered Elements": ["Evocationist", "Steel-infused", "Chaosweaver"],
    "Trickster": ["Overcharged", "Assassin", "Echoist"],
    "Soul Eater": ["Necromancer", "Soul Conduit", "Gargantuan"],
    "Tukohama-touched": ["Bonebreaker", "Executioner", "Magma Barrier"],
    "Corpse Detonator": ["Necromancer", "Incendiary"],
    "Abberath-touched": ["Flame Strider", "Frenzied", "Rejuvenating"],
    "Lunaris-touched": ["Frost Strider", "Invulnerable", "Empowering Minions"],
    "Solaris-touched": ["Invulnerable", "Magma Barrier", "Empowering Minions"],
    "Arakaali-touched": ["Corpse Detonator", "Entangler", "Assassin"],
    "Innocence-touched": ["Lunaris-touched", "Solaris-touched", "Mirror Image", "Mana Siphoner"],
    "Shakari-touched": ["Entangler", "Soul Eater", "Drought Bringer"],
    "Kitava-touched": ["Abberath-touched", "Tukohama-touched", "Corrupter", "Corpse Detonator"],
    "Brine King-touched": ["Ice Prison", "Storm Strider", "Heralding Minions"],
}

export default MONSTER_RECIPES;